{
 "title": "Nina Dashboard",
 "description": "Observatory Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "nina", "label": "Nina", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Nina Weather Reporting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sky Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nina_weather_skytemperature{job=\"$nina\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Sky Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nina_weather_skytemperature{job=\"nina-jst\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is Safe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nina_safety_issafe{job=\"nina-jst\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "options": {
    "content": "<img src=\"http://10.147.19.69/preview.jpg\" id=\"imageToUpdate\" />\r\n<script language=\"javascript\">\r\nfunction updateImage() {\r\n   image = document.getElementById(\"imageToUpdate\");\r\n   image.src = \"http://10.147.19.69/preview.jpg\" + \"?r=\" + Math.random();\r\n   setTimeout(updateImage, 15000);\r\n}\r\nupdateImage();\r\n</script>"
   }
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nina_weather_temperature{job=\"$nina\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nina_weather_temperature{job=\"nina-jst\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dome",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nina_dome_shutter{job=\"nina-jst\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nina Imaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HFR",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "nina_image_hfr{job=\"$nina\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RMS (arc)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "arcsec" } },
   "targets": [
    {
     "expr": "nina_guider_rms_total_arc{job=\"$nina\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "nina_guider_ra_arc{job=\"nina-jst\"}",
     "legendFormat": "RA"
    },
    {
     "expr": "nina_guider_dec_arc{job=\"nina-jst\"}",
     "legendFormat": "Dec"
    }
   ]
  },
  {
   "title": "Mean",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "nina_image_mean{job=\"$nina\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "nina_image_stars{job=\"$nina\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nina Running",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "nina_up{job=\"$nina\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nina_image_hfr{job=\"$nina\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}